apiVersion: v1
kind: Service
metadata:
  name: ygrene-manager-service
  namespace: demo
  labels:
    app: ygrene-manager
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 3000
  selector:
    app: ygrene-manager